### ISSUE TITLE
Allow product team to share credentials with the dev team

### ISSUE THREAD

**Issue by lacostenycoder** [thoroughcare/aptible-server-config#18]
We determined the most secure way to use Vault will be for super admins to access it via JWT auth from the main app since we already have 2FA configured on it, this provides an added layer of security. 

We can use an EC2 instance for that, vault doesn't contain any PHI so we don't need to be on Aptible

**Comment by phbissiwu** [comment]
AWS has a service called `AWS secret manager` we can consider this for secrets, it allows automatic secret rotation, secrets can be encrypted and many more.

**Comment by phbissiwu** [comment]
The wiki for the AWS secret manager is [here](https://github.com/thoroughcare/thoroughcare/wiki/AWS-Secret-Manager-for-Thoroughcare-Credentials)
Let me know if there is anything else you would like me to add.
