### ISSUE TITLE
Move deployer scripts to new repo

### ISSUE THREAD

**Issue by lacostenycoder** [thoroughcare/aptible-server-config#5]
@lacostenycoder commented on [Fri Nov 30 2018](https://github.com/thoroughcare/scale-testing/issues/28)

Currently we keep all the nightly deploys scripts in the main repo.
This adds complexity to the main app which have nothing to do directly with the app code base. As such, these scripts should be moved to this repo or a new repo.

Even though it's not part of scale testing, it is related to scaling so it might make sense to maintain them here.

---

@lacostenycoder commented on [Thu Sep 19 2019](https://github.com/thoroughcare/scale-testing/issues/28#issuecomment-533203258)

Since this is more related to aptible than just scale specific, move this to aptible-server-config repo.

**Comment by radilr1** [comment]
as we discussed on the dev meeting each repo should have its own .circleCI config
